= Configure Setup urxvt

== Handy commands

.Check your locale configuration
[source, bash]
----
>> locale -a
C
C.UTF-8
en_AU
en_AU.iso88591
POSIX
----

.Check if urxvt is configured with fontconfig
[source, bash]
----
>> ldd /usr/bin/urxvt | grep fontconfig
libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f890e417000)
----


sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/urxvt 100



# update-alternatives --config x-terminal-emulator
There are 5 choices for the alternative x-terminal-emulator (providing /usr/bin/x-terminal-emulator).

  Selection    Path                 Priority   Status
------------------------------------------------------------
* 0            /usr/bin/lxterm       30        auto mode
  1            /usr/bin/koi8rxterm   20        manual mode
  2            /usr/bin/lxterm       30        manual mode
  3            /usr/bin/urxvt        20        manual mode
  4            /usr/bin/uxterm       20        manual mode
  5            /usr/bin/xterm        20        manual mode

Press enter to keep the current choice[*], or type selection number:





To figure out xft and fontconfig took me quite a bit of trial and error.  ' man fc-list' is not very helpful, the docs in '/usr/share/doc/fontconfig/' are better.  'fc-list' lists more than just TTF and OTF fonts.

$ fc-list : | sort   ## list all fonts and styles known to fontconfig
$ fc-list -f "%{family}\n" :lang=ja    ## list all japanese font families
$ fc-list -f "%{family} : %{file}\n" :spacing=100 | sort    ## list monospace fonts by family and file
$ fc-list :style=Bold | sort    ## all bold fonts
# fc-list -f "%{file} " | xargs pacman -Qqo | sort -u    ## list font packages installed by pacman
It was not an easy Google search to find examples when I first tried to learn how to use fc-list.




http://www.futurile.net/2016/06/14/xterm-setup-and-truetype-font-configuration/
=== Find a font that you like
Use fc-list or gnome-font-viewer to view true type fonts. Advice to use xlsfonts or xfontsel is to view old style bitmapped, fixed width fonts. The first line below is the best one to use as this will show you the true type fonts that are installed which have a mono spacing option.

# print out the fixed width fonts that are available with their family name
fc-list :scalable=true:spacing=mono: family

# sort and page through the available fonts - not only fixed width fonts
$ fc-list | cut -f2 -d| | sort -u | less

# grep for a specific font
$ fc-list | grep Ubuntu






To see a list of known Fontconfig fonts:

$ fc-list : file

To find and sort installed fonts into sets, I use 'fc-list'.  Unfortunately, the man page for 'fc-list' is so spare it's not very useful.

Monospace fonts all have spacing=100.  To find the monospace font families use:

$ fc-list -f "%{family}\n" :spacing=100


To find by language, use the ISO 639-1 codes, http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes.  The following finds Japanese fonts:

$ fc-list -f "%{family}\n" :lang=ja    # zh-Chinese, ko-Korean, ru-Russian, el-Greek

To list all font packages installed using pacman (this may take a few seconds to produce output):

# fc-list -f "%{file} " | xargs pacman -Qqo | sort -u


@karol - thanks for that tip.  Any idea how to string together a change for both regular and bold fonts?  For example, the following will remove all bolding:

URxvt.keysym.M-C-1: command:\033]710;xft:ubuntu mono:size=14\007\033]711;xft:ubuntu mono:size=14\007




URxvt.keysym.C-0: command:\033]710;xft:Hack:size=10:antialias=true\007
means that when Ctrl-0 is pressed:

\033] - send fake keystroke ESC-] (this announces a terminal control sequence)
710; - terminal control: set normal font, followed by the font description
\077 - end command

Other font control sequences are:

711; - set bold font
712; - set italic font
713; - set bold/italic font

So if you want to set normal and bold at the same time, you can just chain control sequences together:

URxvt.keysym.C-0: command:\033]710;xft:Hack:size=10:antialias=true\007\033]711;xft:Hack:size=10:bold:antialias=true\007
I only know the font control numbers off the top of my head; the others (like character spacing etc.) are probably somewhere in the urxvt docs.

Edit: I found the docs in man 7 urxvt and they explain why 50; doesn't work. 50; sets a new entire fontset (normal, bold, italic) and can dynamically increase/decrease font sizes, but it seems to work only for X11 fontsets (dashes and stars), not xft fonts. So AFAIK chaining multiple font sequences is the way to go (it works for me).


~ $ cat ~/bin/fsize
#!/bin/bash
printf '\33]50;%s%d\007' "xft:Terminus:pixelsize=" $1



https://wiki.archlinux.org/index.php/Rxvt-unicode#Configuration
